### ISSUE TITLE
HashMap 介绍的 link 需要更新啦

### ISSUE THREAD

**Issue by Anonymous-fe** [Omooo/Android-Notes#11]

**Comment by Omooo** [comment]
非常感谢，已经更新了哈～
同时强烈推荐这篇：https://github.com/Omooo/Android-Notes/blob/master/blogs/Java/%E5%8F%A3%E6%B0%B4%E8%AF%9D/%E9%9B%86%E5%90%88%E6%BA%90%E7%A0%81.md
感谢阅读～
