### ISSUE TITLE
請問加殼

### ISSUE THREAD

**Issue by CMingTseng** [Omooo/Android-Notes#4]
你好

有幸拜讀這篇

https://github.com/Omooo/Android-Notes/blob/master/blogs/Android/Gradle/%E4%BE%9D%E8%B5%96%E6%9D%83%E9%99%90%E4%BF%A1%E6%81%AF.md

https://github.com/Omooo/Android-Notes/blob/master/blogs/Android/Gradle/Android%20Plugin%20%E4%B8%BB%E8%A6%81%20Task%20%E5%88%86%E6%9E%90.md

但是這篇是 Android Gradle plugin (AGP) 2.X時代

目前已經到  AGP 3.6.1 (3.1.4~3.5.3-36.1)

有些class消失

請問有新的流程？

因為https://github.com/godlikewangjun/dexknife-wj 遭遇版本升級問題

其中 調整 android-maven-gradle-plugin 後可以編譯

但是 AndroidBuilder消失 ?

請問可以指點一下？

謝謝

**Comment by Omooo** [comment]
晚上回去我看一下，谢谢支持撒～




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Neo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 中午1:57
收件人:&nbsp;"Omooo/Android-Notes"<Android-Notes@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Omooo/Android-Notes] 請問加殼 (#4)





 
你好
 
有幸拜讀這篇
 
https://github.com/Omooo/Android-Notes/blob/master/blogs/Android/Gradle/%E4%BE%9D%E8%B5%96%E6%9D%83%E9%99%90%E4%BF%A1%E6%81%AF.md
 
https://github.com/Omooo/Android-Notes/blob/master/blogs/Android/Gradle/Android%20Plugin%20%E4%B8%BB%E8%A6%81%20Task%20%E5%88%86%E6%9E%90.md
 
但是這篇是 Android Gradle plugin (AGP) 2.X時代
 
目前已經到&nbsp; AGP 3.6.1 (3.1.4~3.5.3-36.1)
 
有些class消失
 
請問有新的流程？
 
因為https://github.com/godlikewangjun/dexknife-wj&nbsp;遭遇版本升級問題
 
其中 調整&nbsp;android-maven-gradle-plugin 後可以編譯
 
但是&nbsp;AndroidBuilder消失 ?
 
請問可以指點一下？
 
謝謝

**Comment by CMingTseng** [comment]
> 晚上回去我看一下，谢谢支持撒～
> […](#)
 感謝大神

我有寄信到你的QQ信箱

敢問大神有W可以聯繫 ?

謝謝

**Comment by CMingTseng** [comment]
大神

我有gradle問題請教

請問怎麼改寫 ？
