### ISSUE TITLE
关于JVM 相关口水话

### ISSUE THREAD

**Issue by bkleopold** [Omooo/Android-Notes#7]
读了《关于JVM 相关口水话》这篇，感觉很不错。是否考虑增加HotSpot 虚拟机方法区实现(JDK7是永久代，JDK8是元空间)区别的相关内容？感觉这块在面试中被问及的还是挺频繁的。

**Comment by Omooo** [comment]
可以的。
当时写口水话的初衷就是为了面试回答用的，所以有些知识点会忽略或者一笔带过。既然这个面试常问，那我晚上就会把它加上去。
PS：
在 Android 和 Java 以及 computer_network 目录下，都有相关口水话。可以帮我校验一蛤~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Omooo/Android-Notes"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月29日(星期三) 上午10:15
收件人:&nbsp;"Omooo/Android-Notes"<Android-Notes@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Omooo/Android-Notes] 关于JVM 相关口水话 (#7)





 
读了《关于JVM 相关口水话》这篇，感觉很不错。是否考虑增加HotSpot 虚拟机方法区实现(JDK7是永久代，JDK8是元空间)区别的相关内容？感觉这块在面试中被问及的还是挺频繁的。

**Comment by Omooo** [comment]
已更新~
